app:
  kube_config: /home/xcheng4/.kube/config
  pod_namespace: evd-cia3dviz
  redis_address: 127.0.0.1:6379
  redis_mock: false
  enqueue_session_stream_key: "enqueue_session_test"
  delete_session_stream_key: "delete_session_test"
  gpu_agent_pool_set_key: "GpuNodePools"
  gpu_agent_pool_names: 
    - viz
    - viz1
    - viz2