// Code generated by mockery v2.36.0. DO NOT EDIT.

package ddd

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIEventHandler is an autogenerated mock type for the IEventHandler type
type MockIEventHandler[T IEvent] struct {
	mock.Mock
}

// HandleEvent provides a mock function with given fields: ctx, event
func (_m *MockIEventHandler[T]) HandleEvent(ctx context.Context, event T) error {
	ret := _m.Called(ctx, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockIEventHandler creates a new instance of MockIEventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEventHandler[T IEvent](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEventHandler[T] {
	mock := &MockIEventHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
